        display: 'flex',
        justifyContent: 'flex-start',
        background: 'white',
        color: 'rgb(82, 85, 88)',
        height: '50px',
        borderBottom: '0.8px solid rgba(173, 173, 173, 0.603)',
        paddingTop: '6px',
        paddingBottom: '6px',